name: Stats

on:
  status:
  push:
    branches:
      - master

jobs:
  stats:
    env:
      branch: ci-stats
    if: ${{ (github.ref == 'refs/heads/master' && (github.event.state == 'success' || github.event.state == 'failure') && github.event.context == 'ci/hydra-build:required') }}
    runs-on: ubuntu-20.04
    steps:
      - name: 'â„ Wait for Hydra build'
        uses: rvl/hydra-build-products-action@master
        id: hydra
        with:
          hydra: https://hydra.iohk.io
          statusName: ci/hydra-eval
          jobs: required
          requiredJob: required
          project: Cardano
          jobset: cardano-wallet
          badge: "${{ github.event_name == 'status' && 'yes' || 'no' }}"

      - name: 'ðŸ“¥ Checkout Code'
        uses: actions/checkout@v2

      - name: 'ðŸ“¥ Checkout Stats'
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}
          fetch-depth: 1
          path: _build

      - name: 'ðŸ“˜ Publish Stats'
        if: ${{ github.ref == 'refs/heads/master' }}
        working-directory: _build
        run: |
          echo '${{ steps.hydra.outputs.evaluation }}' > eval.json
          echo '${{ steps.hydra.outputs.builds }}' > builds.json
          echo '${{ steps.hydra.outputs.timings }}' > timings.json
          ../scripts/gh/update-stats.sh '${{ env.branch}}' eval.json builds.json timings.json

      - name: 'ðŸ“› Update Badge'
        if: ${{ github.event_name == 'status' && github.ref == 'refs/heads/master' }}
        working-directory: _build
        run: |
          ../scripts/gh/update-badge.sh '${{ env.branch}}' '${{ steps.hydra.outputs.badge }}'
